name: ucfnwho_assignment
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  geolocator: ^8.2.0
  shake: ^2.0.0
  sensors: ^2.0.3
  maps_launcher: ^2.0.1
  http: ^0.13.4
  collection: ^1.15.0
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  animated_text_kit: ^4.2.1
  flutter_screenutil: ^5.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/hamburger-ga3f78a511_640-american.jpg
    #Image by <a href="https://pixabay.com/users/brenkee-2021352/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1281855">Benjamin Balazs</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1281855">Pixabay</a>
    - images/taco-g68fb49a04_1280-mexican.jpg
    #Image by <a href="https://pixabay.com/users/stina_magnus-1593756/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1018962">stina_magnus</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1018962">Pixabay</a>
    - images/toast-skagen-g20d6e797f_1280-swedish.jpg
    #Image by <a href="https://pixabay.com/users/mariagutebring-9435129/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=5978803">Maria Gutebring</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=5978803">Pixabay</a>
    - images/pizza-g9edef2467_1280-italian.jpg
    #Image by <a href="https://pixabay.com/users/ponce_photography-2473530/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1442945">Aline Ponce</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1442945">Pixabay</a>
    - images/paella-g495d6e653_1280-spanish.jpg
    #Image by <a href="https://pixabay.com/users/estudiowebdoce-1605998/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1167973">EstudioWebDoce</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1167973">Pixabay</a>
    - images/food-g34fd8a3b8_1280-british.jpg
    #Image by <a href="https://pixabay.com/users/chongodog-9221471/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3687804">chongodog</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3687804">Pixabay</a>
    - images/fish-g33be0ef20_1280-thai.jpg
    #Image by <a href="https://pixabay.com/users/qimono-1962238/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2105233">Arek Socha</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2105233">Pixabay</a>
    - images/sushi-g37aaa190d_1280-japanese.jpg
    #Image by <a href="https://pixabay.com/users/juangallardosevilla-5523047/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2455981">Juan Emilio López Gallardo</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2455981">Pixabay</a>
    - images/dim-sum-g9d5f56483_1280-chinese.jpg
    #Image by <a href="https://pixabay.com/users/chaliceks-2520659/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2346105">Alice Cheung</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2346105">Pixabay</a>
    - images/indian-food-g6c052f420_1280-indian.jpg
    #Image by <a href="https://pixabay.com/users/artificialog-1886751/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3856050">ArtificialOG</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3856050">Pixabay</a>
    - images/quiche-ga9a0acea2_1280-french.jpg
    #Image by <a href="https://pixabay.com/users/ritae-19628/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1579383">RitaE</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1579383">Pixabay</a>
    - images/hummus-g95f7428ed_1280-greek.jpg
    #Image by <a href="https://pixabay.com/users/jcvelis-1672106/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1649231">Jeff Velis</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1649231">Pixabay</a>
    - images/alum-gf52e26a7b_1280-korean.jpg
    #Image by <a href="https://pixabay.com/users/jyleen21-738506/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=749358">jyleen21</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=749358">Pixabay</a>
    - images/middle-eastern-food-gb320d4da1_1280-turkish.jpg
    #Image by <a href="https://pixabay.com/users/timokefoto-4967261/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=6615971">timokefoto</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=6615971">Pixabay</a>
    - images/cafe-g8ca6d84c5_1280-homepage-background.jpg
    #Image by <a href="https://pixabay.com/users/3888952-3888952/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1872888">3888952</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1872888">Pixabay</a>
    - images/icons8-about-100.png
    #<a target="_blank" href="https://icons8.com/icon/3439/about">About</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
    - images/icons8-hungry-100.png
    #<a target="_blank" href="https://icons8.com/icon/bSUU2CsAJypm/hungry">Hungry</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
    - images/icons8-lottery-100.png
    #<a target="_blank" href="https://icons8.com/icon/38yd4ysLmGRK/lottery">Lottery</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
    - images/icons8-booking-100.png
    #<a target="_blank" href="https://icons8.com/icon/78945/booking">Booking</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
    - images/table-g11cd0446b_1280-aboutpage-background.jpg
    #Image by <a href="https://pixabay.com/users/kaboompics-1013994/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=791167">Karolina Grabowska</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=791167">Pixabay</a>
    - images/lisbon-g5dff67bcb_1920-locatePage-background.jpg
    #Image by <a href="https://pixabay.com/users/richardmc-1834381/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2660748">Richard Mcall</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2660748">Pixabay</a>
    - images/house-g219df3e8a_1920-locatePage-background.jpg
    #Image by <a href="https://pixabay.com/users/jirreaux-14740159/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=5632318">Jirreaux Hiroé</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=5632318">Pixabay</a>
    - images/bistro-gfe17ee854_1280-drawResultPage-background.jpg
    #Image by <a href="https://pixabay.com/users/skitterphoto-324082/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=498504">Rudy and Peter Skitterians</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=498504">Pixabay</a>
    - images/country-g1b8c1f462_1280-reserveFormPage-background.jpg
    #Image by <a href="https://pixabay.com/users/mikes-photography-1860391/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2483728">Mikes-Photography</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2483728">Pixabay</a>

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
